Only call restore_orig_conf.sh if it exists
Here was the error when trying to remove RavenCore when the
directory was removed before the rpm erase:

    # rpm -e ravencore
    /var/tmp/rpm-tmp.25599: line 13: /usr/local/ravencore/sbin/restore_orig_conf.sh: No such file or directory
    error: %preun(ravencore-0.3.6-0.1250376601.noarch) scriptlet failed, exit status 127

This makes the "ravencore" packge not get removed, and a call
to "rpm -e --noscripts" is required.

This should fix it.